server:
    port: 8080

spring:
  datasource:
    # 개선 커넥션 풀 db사용
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/scott
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: tiger
#      jdbc-url: jdbc:postgresql://localhost:5432/postgres
#      driver-class-name: org.postgresql.Driver
#      username: docker
#      password: docker
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      # create / create-drop / update / validate / none
      ddl-auto: none
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

graphql:
  servlet:
    enabled: true
    mapping: /graphql
    corsEnabled: false
    cors:
      allowed-origins: http://localhost:8080
      allowed-methods: GET, HEAD, POST, PATCH
    exception-handlers-enabled: true
    context-setting: PER_REQUEST_WITH_INSTRUMENTATION
    async-mode-enabled: true
  tools:
    schema-location-pattern: "**/*.graphqls"
    introspection-enabled: true