package com.study.javabasic.domain;

public enum ScreenCodeEnum {
    SCREEN_CODE_PC,
    SCREEN_CODE_MOBILE,
    SCREEN_CODE_TABLET,
    SCREEN_CODE_GLOBAL_MOBILE,
    SCREEN_CODE_VIP_PC,
    SCREEN_CODE_VIP_MOBILE,
    SCREEN_CODE_SMART_LG,
    SCREEN_CODE_SMART_SAMSUNG,
    SCREEN_CODE_ANDROIDTV,
    SCREEN_CODE_APPLETV,
    SCREEN_CODE_SMART_TV,
    SCREEN_CODE_STICK ,
    SCREEN_CODE_3RD,
    SCREEN_CODE_FULLHD
}
