###

# curl -X POST -H "Content-Type:application/json" --data "{\"query\" : \"query { getMember(id: 1) {id login_id}}\"}" http://localhost:8080/graphql
POST http://localhost:8080/graphql
Content-Type: application/json

{
  "query": "query { getRecentPosts(count: 1, offset: 1) {id title text category}}"
}
###

###

POST http://localhost:8080/graphql
Content-Type: application/json

{
  "query": "mutation { writePost(title: \"ABC\" text: \"Hello\" category: \"News\") {title text category}}"
}
###